name: PRs reviews reminder

on:
  schedule:
    # Every weekday every 2 hours during working hours, send notification
    - cron: "0 8-17/2 * * 1-5"

jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-reviews-reminder-action@v2.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        webhook-url: 'https://hooks.slack.com/services/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' # Required
        provider: 'slack' # Required (slack or msteams)
        channel: '#ecl-free-talking' # Optional, eg: #general
        github-provider-map: 'wbin0718:U041WE3RDMX, FacerAin:U041WE4P8GZ, ghlrobin:U041HN2FGMR, kyc3492:U041388FBM5, jinmyeongAN:U041HR962M8' # Optional, eg: DavideViolante:UEABCDEFG,foobar:UAABCDEFG
        ignore-label: '' # Optional, eg: no-reminder